In [1]:
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np

In [2]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

Exception: URL fetch failure on http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-labels-idx1-ubyte.gz: None -- [WinError 10061] No connection could be made because the target machine actively refused it

In [12]:
mnist = keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [13]:
x_train[10000]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [14]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [15]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 19s 315us/step - loss: 0.2205 - acc: 0.9341
Epoch 2/5
60000/60000 [==============================] - 18s 308us/step - loss: 0.0985 - acc: 0.9696
Epoch 3/5
60000/60000 [==============================] - 18s 307us/step - loss: 0.0689 - acc: 0.9789
Epoch 4/5
60000/60000 [==============================] - 20s 328us/step - loss: 0.0525 - acc: 0.9829
Epoch 5/5
60000/60000 [==============================] - 19s 310us/step - loss: 0.0439 - acc: 0.9860


In [17]:
model.evaluate(x_test, y_test)

10000/10000 [==============================] - 1s 63us/step


[0.06379579277105804, 0.9828]

In [18]:
import PIL
from PIL import Image

In [21]:
testImage = Image.open("C://Users/583175/Pictures/0BW.jpg")
dim=28
testImage = testImage.resize((dim, dim), PIL.Image.ANTIALIAS)

In [38]:
x_test.shape

(10000, 28, 28)

In [37]:
import numpy as np
testImageArr = np.array(testImage)
testImageArr = testImageArr/255.0
testImageArr

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.99215686, 0.98431373, 0.99215686, 0.98431373,
        0.88235294, 0.87058824, 0.86666667, 0.8745098 , 0.87058824,
        0.88235294, 0.98039216, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.98431373, 0.98431373, 0.98823529, 0.88627451,
        0.12156863, 0.05882353, 0.07058824, 0.08235294, 0.05882353,
        0.23921569, 0.97647059, 1.        , 0.99607843, 1.        ,
        1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.99607843, 1.        , 0.99607843,
        1.        , 0.98039216, 0.96078431, 1.        , 0.49803922,
        0.        , 0.0078

In [40]:
testImageArr = testImageArr.reshape(1, 28, 28)
testImageArr.shape

(1, 28, 28)

In [44]:
prob = model.predict(testImageArr)
prob

array([[3.7758210e-07, 3.4001217e-14, 1.8885644e-02, 1.6084123e-10,
        1.7265185e-26, 9.8110777e-01, 6.0498814e-06, 1.0600297e-07,
        8.7340379e-14, 1.4051308e-15]], dtype=float32)

In [47]:
np.amax(prob)

0.9811078

In [48]:
np.argmax(prob)

5

In [49]:
testImage